#!/bin/bash
#test-file
FILE=~/.bashrc
if [ -e "$FILE" ];then
           if [ -f "$FILE" ];then
                  echo ""$FILE" is a regular file"
            fi
            if [ -d "$FILE" ];then
                   echo ""$FILE" id a directory"
             fi
             if [ -r "$FILE" ];then
                    echo ""$FILE" is readable"
              fi
else
     echo ""$FILE" does not exist"
fi
exit
