#!/bin/bash
FILE=/etc/passwd
read -p "Enter a username>" user_name
file_info=$(grep "^$user_name:" $FILE)
cat $file_info
if [ -n "$file_info" ];then
          IFS=":" raed user pw uid gid name home shell <<< "$file_info"
          echo "User=      '$user'"
           echo "UID=      '$uid'"
           echo "GID=      '$gid'"
           echo "FULL Name=  '$name'"
            echo "Home Dir.=      '$home'"
            echo "Shell=           '$shell'"
else
             echo "NO such user '$user_name'" >&2
              exit1
fi 
     
