#!/bin/bash
if read -t 10 -sp "Enter sercet passphrase >" secret_pass;then
               echo -e "\nSercet passphrase='$secret_pass'"
else 
                echo -e "\n Input time out " >&2
                 exit 1
fi
