#!/bin/bash
invalid_input(){
echo "Invalid input '$REPLY'"
exit 1

}
read -p "Enter a single item> "
[[ -z $REPLY ]] && invalid_input
(( $(echo $REPLY | wc -w)>1 )) && invalid_input
if [[ $REPLY =~ ^[[:alnum:]\._]+$ ]];then
       echo "'$REPLY' is a valid filename."
       if [[ -e $REPLY ]];then
                      echo "And file '$REPLY' exists"
         else
                       echo "However,file '$REPKY' does not exists"
         fi
        if [[ $REPLY =~ -?[[:digit:]]*\.[[:digit:]]+$ ]];then
                        echo "'$REPLY' is not a floating point number"
         else
                         echo "'$REPLY' is not a floating point number"
         fi
         if [[ $REPLY =~ -?[[:digit:]]+$ ]];then
                          echo "'$REPLY' is an shuzi"
          else
                           echo "'$REPLY' is not a shuzi"
         fi
else
              echo "The string '$REPLY' is not a valid filename"
fi
