#!/bin/bash
MAX_VAL=100
min_VAL=1
echo -n "please input an integer->"
read INT
if [[ "$INT" =~ ^-?[0-9]+$ ]];then
                 if [[ INT -ge MIN_VAL && INT -le MAX_VAL ]];then
                               echo "in range"
                 else
                                echo "out of range"
                  fi
else
        echo "not shu" >&2
         exit 1
fi



