#!/bin/bash
#Progrm to output a system information age
title="System information report For $HOSTNAME"
CURRENT_TIME=$(date+"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"
report_uptime(){
cat <<- _EOF_
<H2>System Uptime</H2>
<PRE>$(uptime)</PRE>
_EOF_
return
}
report_disk_space(){
cat <<- _EOF_
<H2>Disk space Utilization</H2>
<PRE>$(df -h)</PRE>
_EOF_
return
}
report_home_space(){
cat <<- _EOF_
<H2>Home space Utilization</H2>
<PRE>$(du -sh /home/*)</PRE>
_EOF_
return
}
cat << _EOF_
<HTML>
  <HEAD>
            <TITLE>$title</Title>
  </HEAD>
<BODY>
   <H1>$title</H1>
   <p>$TIME_STAMP</p>
   $(report_uptime)
   $(report_disk_space)
   $(report_home_space)
</BODY>
</HTML>
_EOF_
