#!/bin/bash
#Progrm to output a system information age
title="System information report For $HOSTNAME"
echo "
<HTML>
  <HEAD>
            <TITLE>$title</Title>
  </HEAD>
<BODY>
   <H1>$title</H1>
</BODY>
</HTML>"
