#!/bin/bash
#Progrm to output a system information age
title="System information report For $HOSTNAME"
CURRENT_TIME=$(date+"%x %r %z")
TIME_STAMP="Generated $CURRENT_TIME,by $USER"
cat << _EOF_
<HTML>
  <HEAD>
            <TITLE>$title</Title>
  </HEAD>
<BODY>
   <H1>$title</H1>
   <p>$TIME_STAMP</p>
</BODY>
</HTML>
_EOF_
